### ISSUE TITLE
Failed to execute script RunApp 

### ISSUE THREAD

**Issue by Nisekoi-1** [akai10tsuki/mkvbatchmultiplex#11]
I am also having the same issue. (Sorry for bad English)
Version 2.1

Default Location (C:/Program Files/)
So, what I did was that i wanted to cancel a job/task so to cancel it, I go the task manager and just "End Task" the task, this was the first time i did this to cancel it. After few seconds i have the Windows blue Screen and then my computer restart. After computer restart i try opening the software but shows "Failed to execute script RunApp". So, i download the lastest version with a clean install but same error. Same with portable version and older versions. Now i can't run the software no matter with version. Could solve this problem please?

**Comment by akai10tsuki** [comment]
Hi,

This is difficult to recreate but even when you do a clean install there is the directory where the configuration is saved.  You can try an deleted that to see if this solve the problem.  The directory is in the home directory for windows it will be C:\Users\<username>\.MKVBatchMultiplex.  When the application starts if the directory is not found it will be recreated.  Some files may have been open and corrupted when the blue screen happened. 

Sorry for the delayed response I have been very busy.

**Comment by Nisekoi-1** [comment]
Thanks!!!! It worked. I delete the files in C:\Users<username>.MKVBatchMultiplex and it worked. Thanks again.
