### ISSUE TITLE
Linux | Launch error

### ISSUE THREAD

**Issue by Marikoscz** [akai10tsuki/mkvbatchmultiplex#14]
When I am trying to launch the multiplex error occurs.
![image](https://user-images.githubusercontent.com/88329663/145706757-72efc388-a78e-4444-84c3-0f9df0ed60e9.png)
How can I fix it?
I am using debian 11 . And python 3.9.2
Thanks a lot

**Comment by akai10tsuki** [comment]
Hi,

This is to let you know that I saw this but unable to work with this until after 12/26/2021.  In January 2022 I really going to continue forward with the project.
