### ISSUE TITLE
Linux Appimage OSError Mediainfo not found.

### ISSUE THREAD

**Issue by heldiho53** [akai10tsuki/mkvbatchmultiplex#15]
Everything is installed. Program starts but starting workers doesn't start a process.. Readthedocs says mediainfo path has to be in path. Well they don't provide what the path variable should be though. But my mediainfo executable is in /usr/bin/mediainfo. /usr/bin is in my path obviously. Actually no version of this program works for me. The git version won't even install even with different python versions from pyenv... Installing via pip in python 3.8.1 clicking start workers doesn't even do anything.

**Comment by heldiho53** [comment]
Well it works perfectly in wine if you install mkvtoolnix in wine aswell, but a working linux native app would be awesome.

**Comment by akai10tsuki** [comment]
Hi,

Can you attach a log file.

**Comment by akai10tsuki** [comment]
HI,

Found the problem this image should work:

[MKVBatchMultiplex-x86_64.AppImage](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.1.0b1.dev4/MKVBatchMultiplex-x86_64.AppImage)

Created and tested on Ubuntu 20.04 LTS virtual machines but should work on other linux releases.  Test machine does not have MediaInfo installed was able to bundle the library on the AppImage.

**Comment by heldiho53** [comment]
> 

This one starts the workers but gives me:
`/usr/bin/mkvmerge: /tmp/.mount_MKVBatafRiuR/bin/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/bin/mkvmerge)`

**Comment by akai10tsuki** [comment]
What linux distro are you using?

**Comment by akai10tsuki** [comment]
[MKVBatchMultiplex](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.1.0b1.dev4/MKVBatchMultiplex-linux.zip)  this is the directory generated by pyinstaller you could try this in the meantime. (Ubuntu 20.04)

**Comment by heldiho53** [comment]
I use arch linux. Maybe unsurprising that it doesn't work for me then.

**Comment by akai10tsuki** [comment]
Closing old issues if still using new version and the problem persist please reopen. New version embeds [MediaInfo](https://mediaarea.net/en/MediaInfo/Download).
