### ISSUE TITLE
[BUG] Again! - Does nothing with some mks (for no specific reason?)

### ISSUE THREAD

**Issue by VegethB** [akai10tsuki/mkvbatchmultiplex#17]
**Paths:**
`Z:\Anime Backups\Nisekoi\S02\XIII's Fansub\[XIII's Fansub] Nisekoi S2 01 Sub ITA - Da ora in poi_Notalo.mks`    (Network path), but it also happens on any folder of a HDD / SSD.
`I:\Tor\[Rakuen Subs] Nisekoi S2\[Rakuen Subs]Nisekoi S2 - 01 [SubITA - Hi10P] [09F2BE90].mkv`

**Logs:**
[MKVBatchMultiplex-Logs.zip](https://github.com/akai10tsuki/mkvbatchmultiplex/files/8986725/MKVBatchMultiplex-Logs.zip)
[FileNames.txt](https://github.com/akai10tsuki/mkvbatchmultiplex/files/8986769/FileNames.txt)

**Files:**
[XIII's Fansub (MKS).zip](https://github.com/akai10tsuki/mkvbatchmultiplex/files/8986740/XIII.s.Fansub.MKS.zip)
~As soon as the up on mega is finished, I also update for the ep.~ https://mega.nz/file/YhNXFDTY#7o22bFCj58O7PW6iqhLZFFtcCOv1KT8jdTjACvdrSfk

**Com:**
```
C:\Users\MSI\Downloads\EXE\mkvtoolnix\mkvmerge.exe --ui-language it --output ^"I:\ttt\[Rakuen Subs]Nisekoi S2 - 01 [SubITA - Hi10P] [09F2BE90].mkv^" --no-chapters --language 0:ja --track-name ^"0:[Rakuen Subs] x264 10bit Web ^(commie^)^" --default-track 0:yes --display-dimensions 0:1280x720 --language 1:ja --track-name ^"1:AAC 2.0 Jpn^" --default-track 1:yes --sub-charset 2:UTF-8 --language 2:it --track-name ^"2:Rakuen Subs ^(Web^)^" --default-track 2:yes ^"^(^" ^"I:\Tor\[Rakuen Subs] Nisekoi S2\[Rakuen Subs]Nisekoi S2 - 01 [SubITA - Hi10P] [09F2BE90].mkv^" ^"^)^" --sub-charset 0:UTF-8 --language 0:it --track-name ^"0:XIII's Fansub ^(Web^)^" ^"^(^" ^"Z:\Anime Backups\Nisekoi\S02\XIII's Fansub\[XIII's Fansub] Nisekoi S2 01 Sub ITA - Da ora in poi_Notalo.mks^" ^"^)^" --title ^"[Rakuen Subs]Nisekoi S2 - 01 - D'Ora In Poi ^& Ti Prego, Notami^" --track-order 0:0,0:1,0:2,1:0
```

**Remarks:**
Eventually I did the batch individually and MkvToolNix pointed out to me that of the MKS 4 and 5 have a character set problem (it continued anyway). It could be the one that blocked the software.

**Comment by akai10tsuki** [comment]
Closing old issues if still using new version and the problem persist please reopen.

**Comment by akai10tsuki** [comment]
Closing old issues if still using new version and the problem persist please reopen.
