### ISSUE TITLE
[REQUEST] Portable version for Windows

### ISSUE THREAD

**Issue by seiya-git** [akai10tsuki/mkvbatchmultiplex#4]
Any chance get portable version?

**Comment by akai10tsuki** [comment]
Portable options added to v2.0.0b1 release:

This is a one executable file copy anywhere and run:

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0b1/MKVBatchMultiplex-2.0.0b1-portable.exe

This is a compressed directory MKVBatchMultiplex the executable is MKVBatchMultiplex\MKVBatchMultiplex.exe it should load faster the single executable creates a temporary directory at startup. This should behave like the install version for the one file all I did were light testing so use this if the one file don't work reliably.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0b1/MKVBatchMultiplex-2.0.0b1-portable-dir.zip

This is a one executable file that opens a console where it may display additional error messages if something is not working.

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.0b1/MKVBatchMultiplex-2.0.0b1-portable-console.exe

If you want to erase the program remember to erase [HOMEDIR]/.MKVBatchMultiplex/*  where the configuration and logs are written the registry is not used for portability to different OSes.
