### ISSUE TITLE
[BUG] Startup Error (2.0.0 Rel): Failed to execute script RunApp

### ISSUE THREAD

**Issue by zFerry98** [akai10tsuki/mkvbatchmultiplex#5]
At startup the app give this error:
![image](https://user-images.githubusercontent.com/17975351/93005197-13b3e680-f54f-11ea-8381-883d1bbc0586.png)
.
It's a upgraded from 2.0.0dev.
Windows 10 (2004) Pro.
Install Directory Disk D:\Programmi\*

**Comment by akai10tsuki** [comment]
Hot-fix:

https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v2.0.2/MKVBatchMultiplex-2.0.2-iss-AMD64.exe

I am having trouble with pyinstaller the module that creates the windows binaries.

There will be a development release in 2 or 3 days.  The program will be more flexible when the file structure does not match it will try to get the best track even out of order.

**Comment by Nisekoi-1** [comment]
I am also having the same issue. (Sorry for bad English)
Version 2.1

Default Location (C:/Program Files/)
So, what I did was that i wanted to cancel a job/task so to cancel it, I go the task manager and just the task, this was the first time i did this to cancel it. After few seconds i have the Windows blue Screen and then my computer restart. After computer restart i try opening the software but shows "Failed to execute script RunApp". So, i download the lastest version with a clean install but same error. Same with portable version and older versions. Now i can't run the software no matter with version. Could solve this problem please?
